version: '3.8'

services:
  # ==========================================
  # 1. BASES DE DONNÉES (Isolées par domaine)
  # ==========================================
  db_auth:
    image: postgres:15-alpine
    container_name: agency_db_auth
    environment:
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: secure_auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - agency_network

  db_queue:
    image: postgres:15-alpine
    container_name: agency_db_queue
    environment:
      POSTGRES_USER: queue_admin
      POSTGRES_PASSWORD: secure_queue_pass
      POSTGRES_DB: queue_db
    volumes:
      - queue_data:/var/lib/postgresql/data
    networks:
      - agency_network

  # ==========================================
  # 2. MICROSERVICES BACKEND
  # ==========================================
  auth_service:
    build: ./auth_service
    container_name: agency_auth_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth_service:/app
    environment:
      - DB_HOST=db_auth
      - DB_USER=auth_admin
      - DB_PASS=secure_auth_pass
      - DB_NAME=auth_db
    depends_on:
      - db_auth
    networks:
      - agency_network

  queue_service:
    build: ./queue_service
    container_name: agency_queue_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./queue_service:/app
    environment:
      - DB_HOST=db_queue
      - DB_USER=queue_admin
      - DB_PASS=secure_queue_pass
      - DB_NAME=queue_db
    depends_on:
      - db_queue
    networks:
      - agency_network

  sync_service:
    build: ./sync_service
    container_name: agency_sync_service
    # Ce service tournera en tâche de fond (worker) pour Kafka
    command: python worker.py 
    volumes:
      - ./sync_service:/app
    environment:
      - CENTRAL_KAFKA_BROKER=kafka.siege-central.com:9092 # L'adresse du siège
      - DB_HOST=db_queue # Il lit la DB queue pour faire ses stats
    networks:
      - agency_network

  # ==========================================
  # 3. FRONTEND & API GATEWAY
  # ==========================================
  frontend:
    build: ./frontend_app
    container_name: agency_frontend
    volumes:
      - ./frontend_app:/app
    networks:
      - agency_network

  gateway:
    image: nginx:alpine
    container_name: agency_gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_service
      - queue_service
      - frontend
    networks:
      - agency_network

# ==========================================
# 4. VOLUMES ET RÉSEAUX
# ==========================================
networks:
  agency_network:
    driver: bridge

volumes:
  auth_data:
  queue_data: