events {}

http {
    # Indispensable pour que le CSS soit reconnu comme du style
    include mime.types; 

    server {
        listen 80;

        # <-- LE NOUVEAU BLOC EST ICI -->
        # NGINX va chercher les fichiers statiques dans le volume partagé
        location /static/ {
            alias /app/staticfiles/;
        }

        # 1. Tout ce qui concerne l'authentification va vers l'auth_service
        location /api/auth/ {
            proxy_pass http://auth_service:8000;
            proxy_set_header Host $host;
        }

        # L'interface d'administration Django de l'auth_service
        location /admin/ {
            proxy_pass http://auth_service:8000;
            proxy_set_header Host $host;
        }

        # 2. Tout le reste de l'API (tickets, guichets) va vers le queue_service
        location /api/ {
            proxy_pass http://queue_service:8000;
            proxy_set_header Host $host;
        }

        # 3. Tout le reste du trafic web va vers l'application Next.js
        location / {
            proxy_pass http://frontend_app:3000;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade; # Requis pour le rafraîchissement automatique de Next.js
            proxy_set_header Connection "upgrade";
        }
    }
}