# gateway/nginx.conf
events {}

http {
    server {
        listen 80;

        # 1. Tout ce qui concerne l'authentification va vers l'auth_service
        location /api/auth/ {
            proxy_pass http://auth_service:8000;
            proxy_set_header Host $host;
        }

        # L'interface d'administration Django de l'auth_service
        location /admin/ {
            proxy_pass http://auth_service:8000;
            proxy_set_header Host $host;
        }

        # 2. Tout le reste de l'API (tickets, guichets) va vers le queue_service
        location /api/ {
            proxy_pass http://queue_service:8000;
            proxy_set_header Host $host;
        }
    }
}