# Generated by Django 6.0.6 on 2026-07-16 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Banque',
            fields=[
                ('Bnq_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('Bnq_nom', models.CharField(max_length=100)),
                ('Bnq_code', models.CharField(max_length=20, unique=True)),
                ('Bnq_siegeSocial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='T_File',
            fields=[
                ('FI_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('FI_code', models.CharField(max_length=20)),
                ('FI_nom', models.CharField(max_length=100)),
                ('FI_priorite', models.IntegerField(default=0)),
                ('FI_statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_ServiceMetier',
            fields=[
                ('SM_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('SM_nom', models.CharField(max_length=100)),
                ('SM_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='T_Agence',
            fields=[
                ('Agc_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('Agc_nom', models.CharField(max_length=100)),
                ('Agc_adresse', models.CharField(max_length=255)),
                ('Agc_statut', models.CharField(max_length=50)),
                ('Agc_synchronisationActive', models.BooleanField(default=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agences', to='core.t_banque')),
            ],
        ),
        migrations.CreateModel(
            name='T_Guichet',
            fields=[
                ('G_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('G_numero', models.IntegerField()),
                ('G_statut', models.CharField(max_length=50)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guichets', to='core.t_agence')),
            ],
        ),
        migrations.CreateModel(
            name='T_AffectationGuichet',
            fields=[
                ('AG_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('U_id_agent', models.CharField(max_length=50)),
                ('AG_dateDebut', models.DateTimeField(auto_now_add=True)),
                ('AG_dateFin', models.DateTimeField(blank=True, null=True)),
                ('AG_actif', models.BooleanField(default=True)),
                ('file_attente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.t_file')),
                ('guichet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.t_guichet')),
            ],
        ),
        migrations.AddField(
            model_name='t_file',
            name='service_metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.t_servicemetier'),
        ),
        migrations.CreateModel(
            name='T_Ticket',
            fields=[
                ('T_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('T_numero', models.IntegerField()),
                ('T_dateEmission', models.DateTimeField(auto_now_add=True)),
                ('T_priorite', models.IntegerField(default=0)),
                ('T_statut', models.CharField(max_length=50)),
                ('file_attente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.t_file')),
            ],
        ),
    ]
