# Generated by Django 5.2.15 on 2026-06-26 10:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Debut de la synchronisation')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la synchronisation')),
                ('status', models.CharField(choices=[('PENDING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('PARTIAL', 'Succès partiel')], default='PENDING', max_length=15, verbose_name='Statut')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Nombre de tickets traités')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Rapport d'erreur / Stacktrace")),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Numéro de tentative')),
            ],
            options={
                'verbose_name': 'Historique de synchronisation',
                'verbose_name_plural': 'Historiques de synchronisation',
                'ordering': ['-start_time'],
            },
        ),
    ]
