# Generated by Django 6.0.6 on 2026-07-14 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Fonctionnalite',
            fields=[
                ('F_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('F_code', models.CharField(max_length=50, unique=True)),
                ('F_niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_GroupeUtilisateur',
            fields=[
                ('GU_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('GU_nom', models.CharField(max_length=100, unique=True)),
                ('GU_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('U_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('U_nom', models.CharField(max_length=100)),
                ('U_prenom', models.CharField(max_length=100)),
                ('U_login', models.CharField(max_length=150, unique=True)),
                ('Agc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('groupes', models.ManyToManyField(related_name='utilisateurs', to='accounts.t_groupeutilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='T_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_description', models.CharField(max_length=255)),
                ('fonctionnalites', models.ManyToManyField(related_name='permissions', to='accounts.t_fonctionnalite')),
            ],
        ),
        migrations.AddField(
            model_name='t_groupeutilisateur',
            name='permissions',
            field=models.ManyToManyField(related_name='groupes', to='accounts.t_permission'),
        ),
    ]
