# Generated by Django 6.0.6 on 2026-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='t_utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
